base: '%env(SITE_BASE)%'
baseVariants:
  -
    base: 'https://5d36-169-155-235-244.ngrok-free.app'
    condition: 'applicationContext == "Development"'
dependencies:
  - typo3-incubator/surfcamp-base
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 98
websiteTitle: 'Surfcamp Base'
