indexedsearch:
  targetPid: 3
fcbigfoot:
  pages:
    privacy: 2
    contact: 4
  socialmedia:
    channels:
      instagram:
        link: 'https://www.instagram.com/typo3_official/'
plugin:
  bootstrap_package_contentelements:
    view:
      layoutRootPath: 'EXT:fcbigfoot/Resources/Private/Templates/ContentElements/Layouts/'
      partialRootPath: 'EXT:fcbigfoot/Resources/Private/Templates/ContentElements/Partials/'
      templateRootPath: 'EXT:fcbigfoot/Resources/Private/Templates/ContentElements/Templates/'
